[tool.poetry]
name = "experts_etl"
version = "5.14.1"
description = "Moves data from UMN to Pure (Experts@Minnesota), and vice versa."
readme = "README.md"
authors = ["David Naughton <naughton@umn.edu>", "Michael Berkowski <mjb@umn.edu"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0.0"
experts_dw = {git = "git://github.com/UMNLibraries/experts_dw.git", branch="main", tag="7.17.0"}
jinja2 = ">=2.11.3"
pandas = ">=1.3"
pureapi = {git = "git://github.com/UMNLibraries/pureapi.git", branch="main", tag="4.2.0"}
python-daemon = "*"
dotenv_switch = {git = "git://github.com/UMNLibraries/dotenv_switch.git"}
python-json-logger = "*"
schedule = "*"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "*"
