import datetime

entries = [
  {
    'emplid': '8000397',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2015,9,1,0,0),
    'effseq': '0',
    'position_nbr': '267217',
    'jobcode': '9403',
    'jobcode_descr': 'Assistant Professor',
    'empl_status': 'A',
    'deptid': '11720',
    'status_flg': 'H',
    'job_terminated': 'Y',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'position_entry_dt': datetime.datetime(2015,9,1,0,0),
  },
  {
    'emplid': '8000397',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2015,9,1,0,0),
    'effseq': '0',
    'position_nbr': '267217',
    'jobcode': '9403',
    'jobcode_descr': 'Assistant Professor',
    'empl_status': 'A',
    'deptid': '11720',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'position_entry_dt': datetime.datetime(2015,9,1,0,0),
  },
  {
    'emplid': '8000397',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2015,9,1,0,0),
    'effseq': '2',
    'position_nbr': '267217',
    'jobcode': '9403',
    'jobcode_descr': 'Assistant Professor',
    'empl_status': 'A',
    'deptid': '11720',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'position_entry_dt': datetime.datetime(2015,9,1,0,0),
  },
  {
    'emplid': '8000397',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2016,6,13,0,0),
    'effseq': '0',
    'position_nbr': '267217',
    'jobcode': '9403',
    'jobcode_descr': 'Assistant Professor',
    'empl_status': 'A',
    'deptid': '11720',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'position_entry_dt': datetime.datetime(2015,9,1,0,0),
  },
  {
    'emplid': '8000397',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2016,6,13,0,0),
    'effseq': '1',
    'position_nbr': '267217',
    'jobcode': '9403',
    'jobcode_descr': 'Assistant Professor',
    'empl_status': 'A',
    'deptid': '11720',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'position_entry_dt': datetime.datetime(2015,9,1,0,0),
  },
  {
    'emplid': '8000397',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2017,6,17,0,0),
    'effseq': '0',
    'position_nbr': '267217',
    'jobcode': '9403',
    'jobcode_descr': 'Assistant Professor',
    'empl_status': 'A',
    'deptid': '11720',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'position_entry_dt': datetime.datetime(2015,9,1,0,0),
  },
  {
    'emplid': '8000397',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2017,6,17,0,0),
    'effseq': '1',
    'position_nbr': '267217',
    'jobcode': '9403',
    'jobcode_descr': 'Assistant Professor',
    'empl_status': 'A',
    'deptid': '11720',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'position_entry_dt': datetime.datetime(2015,9,1,0,0),
  },
  {
    'emplid': '8000397',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2018,6,11,0,0),
    'effseq': '0',
    'position_nbr': '267217',
    'jobcode': '9403',
    'jobcode_descr': 'Assistant Professor',
    'empl_status': 'A',
    'deptid': '11720',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'position_entry_dt': datetime.datetime(2015,9,1,0,0),
  },
  {
    'emplid': '8000397',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2018,6,11,0,0),
    'effseq': '1',
    'position_nbr': '267217',
    'jobcode': '9403',
    'jobcode_descr': 'Assistant Professor',
    'empl_status': 'A',
    'deptid': '11720',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'position_entry_dt': datetime.datetime(2015,9,1,0,0),
  },
  {
    'emplid': '8000397',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2018,8,20,0,0),
    'effseq': '0',
    'position_nbr': '267217',
    'jobcode': '9403',
    'jobcode_descr': 'Assistant Professor',
    'empl_status': 'A',
    'deptid': '11720',
    'status_flg': 'C',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'position_entry_dt': datetime.datetime(2015,9,1,0,0),
  },
]

entry_groups = [
  {
    'position_nbr': '267217',
    'job_entry_dt': datetime.datetime(2015,9,1,0,0),
    'jobcode': '9403',
    'deptid': '11720',
    'entries': entries,
  },
]

jobs = [
  {
    'deptid': '11720',
    'org_id': 'AOVMGGA',
    'empl_rcdno': '0',
    'job_title': 'Assistant Professor',
    'employment_type': 'faculty',
    'staff_type': 'academic',
    'start_date': datetime.datetime(2015,9,1,0,0),
    'end_date': None,
    'visibility': 'Public',
    'profiled': True,
  },
]

jobs_with_primary = [
  {**jobs[0], **{'primary': True}}
]

# Set according to the primary job:
transformed_profiled = False

jobs_with_transformed_staff_type = jobs_with_primary

jobs_with_staff_org_assoc_id = [
  {**jobs_with_primary[0], **{'staff_org_assoc_id': 'autoid:8000397-AOVMGGA-Assistant Professor-faculty-2015-09-01'}}
]
