import datetime

entries = [
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2015,4,6,0,0),
    'position_nbr': '250541',
    'jobcode': '9743',
    'jobcode_descr': 'Senior Research Fellow',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2000,11,22,0,0),
    'position_entry_dt': datetime.datetime(2011,5,30,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2015,6,15,0,0),
    'position_nbr': '250541',
    'jobcode': '9743',
    'jobcode_descr': 'Senior Research Fellow',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2000,11,22,0,0),
    'position_entry_dt': datetime.datetime(2011,5,30,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2015,6,15,0,0),
    'position_nbr': '250541',
    'jobcode': '9743',
    'jobcode_descr': 'Senior Research Fellow',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2000,11,22,0,0),
    'position_entry_dt': datetime.datetime(2011,5,30,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2015,9,7,0,0),
    'position_nbr': '250541',
    'jobcode': '9742R7',
    'jobcode_descr': 'Researcher 7',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2011,5,30,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2015,9,21,0,0),
    'position_nbr': '250541',
    'jobcode': '9742R7',
    'jobcode_descr': 'Researcher 7',
    'empl_status': 'P',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': datetime.datetime(2015,9,20,0,0),
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2011,5,30,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2015,11,2,0,0),
    'position_nbr': '250541',
    'jobcode': '9742R7',
    'jobcode_descr': 'Researcher 7',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2011,5,30,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2016,6,13,0,0),
    'position_nbr': '250541',
    'jobcode': '9742R7',
    'jobcode_descr': 'Researcher 7',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2011,5,30,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2016,6,13,0,0),
    'position_nbr': '250541',
    'jobcode': '9742R7',
    'jobcode_descr': 'Researcher 7',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2011,5,30,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2017,6,12,0,0),
    'position_nbr': '250541',
    'jobcode': '9742R7',
    'jobcode_descr': 'Researcher 7',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2011,5,30,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2017,6,12,0,0),
    'position_nbr': '250541',
    'jobcode': '9742R7',
    'jobcode_descr': 'Researcher 7',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2011,5,30,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2017,7,10,0,0),
    'position_nbr': '212266',
    'jobcode': '9341M2',
    'jobcode_descr': 'Administrative Manager 2',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'H',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2017,7,10,0,0),
    'position_entry_dt': datetime.datetime(2017,7,10,0,0),
  },
  {
    'emplid': 'fake312',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2017,7,10,0,0),
    'position_nbr': '301101',
    'jobcode': '9341M2',
    'jobcode_descr': 'Administrative Manager 2',
    'empl_status': 'A',
    'deptid': '11179',
    'status_flg': 'C',
    'job_terminated': 'N',
    'last_date_worked': None,
    'job_entry_dt': datetime.datetime(2017,7,10,0,0),
    'position_entry_dt': datetime.datetime(2017,7,10,0,0),
  },
]

entries_by_position_nbr = {
  '250541': entries[0:10],
  '212266': entries[10],
  '301101': entries[11],
}

stints = [
  entries[0:10],
  entries[10],
  entries[11],
]

jobs = [
  {
    'deptid': '11179',
    'org_id': 'PIXEZPPAPIRGQ',
    'empl_rcdno': '0',
    'job_title': 'Researcher 7',
    'employment_type': 'researcher',
    'staff_type': 'academic',
    'primary': False,
    'start_date': datetime.datetime(2000,11,22,0,0),
    'end_date': datetime.datetime(2017,6,12,0,0),
    'visibility': 'Restricted',
    'profiled': False,
  },
  {
    'deptid': '11179',
    'org_id': 'PIXEZPPAPIRGQ',
    'empl_rcdno': '0',
    'job_title': 'Administrative Manager 2',
    'employment_type': 'academic_administrative',
    'staff_type': 'nonacademic',
    'primary': False,
    'start_date': datetime.datetime(2017,7,10,0,0),
    'end_date': datetime.datetime(2017,7,10,0,0),
    'visibility': 'Restricted',
    'profiled': False,
  },
  {
    'deptid': '11179',
    'org_id': 'PIXEZPPAPIRGQ',
    'empl_rcdno': '0',
    'job_title': 'Administrative Manager 2',
    'employment_type': 'academic_administrative',
    'staff_type': 'nonacademic',
    'primary': True,
    'start_date': datetime.datetime(2017,7,10,0,0),
    'end_date': None,
    'visibility': 'Restricted',
    'profiled': False,
  },
]

jobs_with_staff_org_assoc_id = [
  {
    'staff_org_assoc_id': 'autoid:6030-PIXEZPPAPIRGQ-Researcher 7-researcher-2000-11-22',
    'deptid': '11179',
    'org_id': 'PIXEZPPAPIRGQ',
    'empl_rcdno': '0',
    'job_title': 'Researcher 7',
    'employment_type': 'researcher',
    'staff_type': 'academic',
    'primary': False,
    'start_date': datetime.datetime(2000,11,22,0,0),
    'end_date': datetime.datetime(2017,6,12,0,0),
    'visibility': 'Restricted',
    'profiled': False,
  },
  {
    'staff_org_assoc_id': 'autoid:6030-PIXEZPPAPIRGQ-Administrative Manager 2-academic_administrative-2017-07-10',
    'deptid': '11179',
    'org_id': 'PIXEZPPAPIRGQ',
    'empl_rcdno': '0',
    'job_title': 'Administrative Manager 2',
    'employment_type': 'academic_administrative',
    'staff_type': 'nonacademic',
    'primary': True,
    'start_date': datetime.datetime(2017,7,10,0,0),
    'end_date': None,
    'visibility': 'Restricted',
    'profiled': False,
  },
]
