import datetime

entries = [
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2002,1,22,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '803A',
    'jobcode': '8635',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'HIR',
    'action_descr': 'Hire',
    'action_dt': datetime.datetime(2002,1,17,0,0),
    'action_reason': 'EXT',
    'action_reason_descr': 'New Employee-External Hire',
    'job_entry_dt': datetime.datetime(2002,1,22,0,0),
    'dept_entry_dt': datetime.datetime(2002,1,22,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2002,5,6,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '803A',
    'jobcode': '8635',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2002,5,21,0,0),
    'action_reason': 'INR',
    'action_reason_descr': 'In-range',
    'job_entry_dt': datetime.datetime(2002,1,22,0,0),
    'dept_entry_dt': datetime.datetime(2002,1,22,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2002,6,17,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '803A',
    'jobcode': '8635',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2002,6,16,0,0),
    'action_reason': 'ANU',
    'action_reason_descr': 'Annual Increase',
    'job_entry_dt': datetime.datetime(2002,1,22,0,0),
    'dept_entry_dt': datetime.datetime(2002,1,22,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2002,10,7,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '803A',
    'jobcode': '8635',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2002,11,4,0,0),
    'action_reason': 'INR',
    'action_reason_descr': 'In-range',
    'job_entry_dt': datetime.datetime(2002,1,22,0,0),
    'dept_entry_dt': datetime.datetime(2002,1,22,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2002,11,18,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '803A',
    'jobcode': '8636',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'JRC',
    'action_descr': 'Job Reclassification',
    'action_dt': datetime.datetime(2002,11,11,0,0),
    'action_reason': 'PRO',
    'action_reason_descr': 'Promotion',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'dept_entry_dt': datetime.datetime(2002,1,22,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2004,6,14,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '804A',
    'jobcode': '8636',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2004,6,14,0,0),
    'action_reason': 'ANU',
    'action_reason_descr': 'Annual Increase',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'dept_entry_dt': datetime.datetime(2003,6,16,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2004,9,6,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '804A',
    'jobcode': '8636',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'DTA',
    'action_descr': 'Data Change',
    'action_dt': datetime.datetime(2004,9,9,0,0),
    'action_reason': 'SPC',
    'action_reason_descr': 'Special Circumstances',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'dept_entry_dt': datetime.datetime(2003,6,16,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2004,12,13,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '804A',
    'jobcode': '8636',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2004,12,13,0,0),
    'action_reason': 'ANU',
    'action_reason_descr': 'Annual Increase',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'dept_entry_dt': datetime.datetime(2003,6,16,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2005,6,13,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '804A',
    'jobcode': '8636',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2005,6,13,0,0),
    'action_reason': 'ANU',
    'action_reason_descr': 'Annual Increase',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'dept_entry_dt': datetime.datetime(2003,6,16,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2005,6,13,0,0),
    'effseq': '1',
    'status_flg': 'H',
    'deptid': '804A',
    'jobcode': '8636',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2006,1,1,0,0),
    'action_reason': 'ANU',
    'action_reason_descr': 'Annual Increase',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'dept_entry_dt': datetime.datetime(2003,6,16,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2006,6,12,0,0),
    'effseq': '2',
    'status_flg': 'H',
    'deptid': '804A',
    'jobcode': '8636',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'POS',
    'action_descr': 'Position Change',
    'action_dt': datetime.datetime(2006,10,11,0,0),
    'action_reason': 'CNV',
    'action_reason_descr': 'Position Conversion',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'dept_entry_dt': datetime.datetime(2003,6,16,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2006,6,12,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '804A',
    'jobcode': '8636',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2006,6,12,0,0),
    'action_reason': 'ANU',
    'action_reason_descr': 'Annual Increase',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'dept_entry_dt': datetime.datetime(2003,6,16,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2006,6,12,0,0),
    'effseq': '1',
    'status_flg': 'H',
    'deptid': '804A',
    'jobcode': '8636',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2006,6,15,0,0),
    'action_reason': 'INR',
    'action_reason_descr': 'In-range',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'dept_entry_dt': datetime.datetime(2003,6,16,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2006,12,9,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '804A',
    'jobcode': '8636',
    'jobcode_descr': 'Info Tech Prof',
    'empl_status': 'T',
    'action': 'TER',
    'action_descr': 'Termination',
    'action_dt': datetime.datetime(2006,11,29,0,0),
    'action_reason': 'PER',
    'action_reason_descr': 'Personal/Unknown',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'dept_entry_dt': datetime.datetime(2003,6,16,0,0),
    'job_terminated': 'N',
    'position_nbr': '200160',
    'position_entry_dt': datetime.datetime(2006,10,11,0,0),
    'last_date_worked': datetime.datetime(2006,12,8,0,0),
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2008,3,31,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '372A',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'REH',
    'action_descr': 'Rehire',
    'action_dt': datetime.datetime(2008,3,26,0,0),
    'action_reason': 'BRK',
    'action_reason_descr': 'Rehire after 30 Days',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '220465',
    'position_entry_dt': datetime.datetime(2008,3,31,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2008,6,9,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'DTA',
    'action_descr': 'Data Change',
    'action_dt': datetime.datetime(2008,6,14,0,0),
    'action_reason': 'CNV',
    'action_reason_descr': 'Conversion',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '220465',
    'position_entry_dt': datetime.datetime(2008,3,31,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2008,8,4,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'DTA',
    'action_descr': 'Data Change',
    'action_dt': datetime.datetime(2008,7,29,0,0),
    'action_reason': 'POS',
    'action_reason_descr': 'Position',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '220403',
    'position_entry_dt': datetime.datetime(2008,8,4,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2010,6,7,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2010,6,12,0,0),
    'action_reason': 'TRP',
    'action_reason_descr': 'Temporary Reduction in Pay',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '220403',
    'position_entry_dt': datetime.datetime(2008,8,4,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2011,1,3,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2010,10,11,0,0),
    'action_reason': 'MER',
    'action_reason_descr': 'Merit',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '220403',
    'position_entry_dt': datetime.datetime(2008,8,4,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2011,5,2,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'DTA',
    'action_descr': 'Data Change',
    'action_dt': datetime.datetime(2011,5,5,0,0),
    'action_reason': 'POS',
    'action_reason_descr': 'Position',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '220465',
    'position_entry_dt': datetime.datetime(2011,5,2,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2011,6,20,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2010,11,6,0,0),
    'action_reason': 'TRR',
    'action_reason_descr': 'Temp Pay Reduction Restoration',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '220465',
    'position_entry_dt': datetime.datetime(2011,5,2,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2012,6,18,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2012,6,29,0,0),
    'action_reason': 'MER',
    'action_reason_descr': 'Merit',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '220465',
    'position_entry_dt': datetime.datetime(2011,5,2,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2012,10,29,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'DTA',
    'action_descr': 'Data Change',
    'action_dt': datetime.datetime(2012,11,9,0,0),
    'action_reason': 'POS',
    'action_reason_descr': 'Position',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '256774',
    'position_entry_dt': datetime.datetime(2012,10,29,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2012,12,31,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'DTA',
    'action_descr': 'Data Change',
    'action_dt': datetime.datetime(2012,10,25,0,0),
    'action_reason': 'BEN',
    'action_reason_descr': 'Benefits Use Only',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '256774',
    'position_entry_dt': datetime.datetime(2012,12,31,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2013,6,17,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9775',
    'jobcode_descr': 'Info Tech Prof (P/A)',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2013,6,17,0,0),
    'action_reason': 'MER',
    'action_reason_descr': 'Merit',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '256774',
    'position_entry_dt': datetime.datetime(2012,12,31,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2013,6,17,0,0),
    'effseq': '1',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9790D3',
    'jobcode_descr': 'Developer 3',
    'empl_status': 'A',
    'action': 'DTA',
    'action_descr': 'Data Change',
    'action_dt': datetime.datetime(2013,7,5,0,0),
    'action_reason': 'SPC',
    'action_reason_descr': 'Special Circumstances',
    'job_entry_dt': datetime.datetime(2013,6,17,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '260291',
    'position_entry_dt': datetime.datetime(2013,6,17,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2013,12,30,0,0),
    'effseq': '0',
    'status_flg': 'H',
    'deptid': '10017',
    'jobcode': '9790D3',
    'jobcode_descr': 'Developer 3',
    'empl_status': 'A',
    'action': 'DTA',
    'action_descr': 'Data Change',
    'action_dt': datetime.datetime(2013,10,24,0,0),
    'action_reason': 'BEN',
    'action_reason_descr': 'Benefits Use Only',
    'job_entry_dt': datetime.datetime(2013,6,17,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '260291',
    'position_entry_dt': datetime.datetime(2013,6,17,0,0),
    'last_date_worked': None,
  },
  {
    'emplid': 'fake123',
    'empl_rcdno': '0',
    'effdt': datetime.datetime(2014,6,16,0,0),
    'effseq': '0',
    'status_flg': 'C',
    'deptid': '10017',
    'jobcode': '9790D3',
    'jobcode_descr': 'Developer 3',
    'empl_status': 'A',
    'action': 'PAY',
    'action_descr': 'Pay Rate Change',
    'action_dt': datetime.datetime(2014,6,26,0,0),
    'action_reason': 'MER',
    'action_reason_descr': 'Merit',
    'job_entry_dt': datetime.datetime(2013,6,17,0,0),
    'dept_entry_dt': datetime.datetime(2008,3,31,0,0),
    'job_terminated': 'N',
    'position_nbr': '260291',
    'position_entry_dt': datetime.datetime(2013,6,17,0,0),
    'last_date_worked': None,
  },
]

entries_by_position_nbr = {
  '200160': entries[0:14],
  '220465': entries[14:16] + entries[19:22],
  '220403': entries[16:19],
  '256774': entries[22:25],
  '260291': entries[25:],
}

entry_groups = [
  {
    'position_nbr': '200160',
    'job_entry_dt': datetime.datetime(2002,1,22,0,0),
    'jobcode': '8635',
    'deptid': '803A',
    'entries': entries[0:4],
  },
  {
    'position_nbr': '200160',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'jobcode': '8636',
    'deptid': '803A',
    'entries': entries[4:5],
  },
  {
    'position_nbr': '200160',
    'job_entry_dt': datetime.datetime(2002,11,18,0,0),
    'jobcode': '8636',
    'deptid': '804A',
    'entries': entries[5:14],
  },
  {
    'position_nbr': '220403',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'jobcode': '9775',
    'deptid': '10017',
    'entries': entries[16:19],
  },
  {
    'position_nbr': '220465',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'jobcode': '9775',
    'deptid': '372A',
    'entries': entries[14:15],
  },
  {
    'position_nbr': '220465',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'jobcode': '9775',
    'deptid': '10017',
    'entries': entries[15:16] + entries[19:22],
  },
  {
    'position_nbr': '256774',
    'job_entry_dt': datetime.datetime(2008,3,31,0,0),
    'jobcode': '9775',
    'deptid': '10017',
    'entries': entries[22:25],
  },
  {
    'position_nbr': '260291',
    'job_entry_dt': datetime.datetime(2013,6,17,0,0),
    'jobcode': '9790D3',
    'deptid': '10017',
    'entries': entries[25:],
  },
]
