import datetime

entries = [
    {
        'emplid': '5231388',
        'empl_rcdno': '2',
        'effdt': datetime.datetime(2016,8,29,0,0),
        'effseq': '0',
        'position_nbr': '295323',
        'jobcode': '9561',
        'jobcode_descr': 'Graduate School Fellow',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2016,8,29,0,0),
        'position_entry_dt': datetime.datetime(2016,8,29,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '2',
        'effdt': datetime.datetime(2017,5,31,0,0),
        'effseq': '0',
        'position_nbr': '295323',
        'jobcode': '9561',
        'jobcode_descr': 'Graduate School Fellow',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2016,8,29,0,0),
        'position_entry_dt': datetime.datetime(2016,8,29,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '2',
        'effdt': datetime.datetime(2017,8,28,0,0),
        'effseq': '0',
        'position_nbr': '295323',
        'jobcode': '9561',
        'jobcode_descr': 'Graduate School Fellow',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2016,8,29,0,0),
        'position_entry_dt': datetime.datetime(2016,8,29,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '2',
        'effdt': datetime.datetime(2017,9,1,0,0),
        'effseq': '0',
        'position_nbr': '295323',
        'jobcode': '9561',
        'jobcode_descr': 'Graduate School Fellow',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2016,8,29,0,0),
        'position_entry_dt': datetime.datetime(2016,8,29,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '2',
        'effdt': datetime.datetime(2018,5,28,0,0),
        'effseq': '0',
        'position_nbr': '295323',
        'jobcode': '9561',
        'jobcode_descr': 'Graduate School Fellow',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2016,8,29,0,0),
        'position_entry_dt': datetime.datetime(2016,8,29,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '3',
        'effdt': datetime.datetime(2018,7,1,0,0),
        'effseq': '0',
        'position_nbr': '307530',
        'jobcode': '9562',
        'jobcode_descr': 'Graduate School Trainee',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2018,7,1,0,0),
        'position_entry_dt': datetime.datetime(2018,7,1,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '2',
        'effdt': datetime.datetime(2018,7,1,0,0),
        'effseq': '0',
        'position_nbr': '295323',
        'jobcode': '9561',
        'jobcode_descr': 'Graduate School Fellow',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2016,8,29,0,0),
        'position_entry_dt': datetime.datetime(2016,8,29,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '2',
        'effdt': datetime.datetime(2019,5,16,0,0),
        'effseq': '0',
        'position_nbr': '295323',
        'jobcode': '9561',
        'jobcode_descr': 'Graduate School Fellow',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2016,8,29,0,0),
        'position_entry_dt': datetime.datetime(2016,8,29,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '3',
        'effdt': datetime.datetime(2019,6,10,0,0),
        'effseq': '0',
        'position_nbr': '307530',
        'jobcode': '9562',
        'jobcode_descr': 'Graduate School Trainee',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2018,7,1,0,0),
        'position_entry_dt': datetime.datetime(2018,7,1,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '2',
        'effdt': datetime.datetime(2019,6,10,0,0),
        'effseq': '0',
        'position_nbr': '295323',
        'jobcode': '9561',
        'jobcode_descr': 'Graduate School Fellow',
        'empl_status': 'T',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2016,8,29,0,0),
        'position_entry_dt': datetime.datetime(2016,8,29,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '3',
        'effdt': datetime.datetime(2019,7,1,0,0),
        'effseq': '0',
        'position_nbr': '307530',
        'jobcode': '9562',
        'jobcode_descr': 'Graduate School Trainee',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2018,7,1,0,0),
        'position_entry_dt': datetime.datetime(2018,7,1,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '2',
        'effdt': datetime.datetime(2019,8,26,0,0),
        'effseq': '0',
        'position_nbr': '295323',
        'jobcode': '9561',
        'jobcode_descr': 'Graduate School Fellow',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'C',
        'job_entry_dt': datetime.datetime(2016,8,29,0,0),
        'position_entry_dt': datetime.datetime(2016,8,29,0,0),
    },
    {
        'emplid': '5231388',
        'empl_rcdno': '3',
        'effdt': datetime.datetime(2019,8,26,0,0),
        'effseq': '0',
        'position_nbr': '307530',
        'jobcode': '9562',
        'jobcode_descr': 'Graduate School Trainee',
        'empl_status': 'A',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'status_flg': 'C',
        'job_entry_dt': datetime.datetime(2018,7,1,0,0),
        'position_entry_dt': datetime.datetime(2018,7,1,0,0),
    },
]

entry_groups = [
    {
        'position_nbr': '295323',
        'job_entry_dt': datetime.datetime(2016,8,29,0,0),
        'jobcode': '9561',
        'deptid': '10858',
        'entries': entries[0:5] + entries[6:8] + entries[9:10] + entries[11:12],
    },
    {
        'position_nbr': '307530',
        'job_entry_dt': datetime.datetime(2018,7,1,0,0),
        'jobcode': '9562',
        'deptid': '10858',
        'entries': entries[5:6] + entries[8:9] + entries[10:11] + entries [12:],
    },
]

jobs = [
    {
        'affiliation_id': '9561',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'org_id': 'PQXWQORJA',
        'empl_rcdno': '2',
        'job_title': 'Graduate School Fellow',
        'job_description': 'Graduate School Fellow',
        'employment_type': 'student',
        'staff_type': 'nonacademic',
        'start_date': datetime.datetime(2016,8,29,0,0),
        'end_date': None,
        'visibility': 'Restricted',
        'profiled': False,
    },
    {
        'affiliation_id': '9562',
        'deptid': '10858',
        'um_campus': 'TXXX',
        'org_id': 'PQXWQORJA',
        'empl_rcdno': '3',
        'job_title': 'Graduate School Trainee',
        'job_description': 'Graduate School Trainee',
        'employment_type': 'student',
        'staff_type': 'nonacademic',
        'start_date': datetime.datetime(2018,7,1,0,0),
        'end_date': None,
        'visibility': 'Restricted',
        'profiled': False,
    },
]
