import datetime

entries = [
    {
        'emplid': '5491169',
        'empl_rcdno': '0',
        'effdt': datetime.datetime(2018,8,27,0,0),
        'effseq': '0',
        'position_nbr': '274940',
        'jobcode': '9561',
        'jobcode_descr': 'Graduate School Fellow',
        'empl_status': 'A',
        'deptid': '11093',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2018,8,27,0,0),
        'position_entry_dt': datetime.datetime(2018,8,27,0,0),
    },
    {
        'emplid': '5491169',
        'empl_rcdno': '0',
        'effdt': datetime.datetime(2019,5,27,0,0),
        'effseq': '0',
        'position_nbr': '286129',
        'jobcode': '9566',
        'jobcode_descr': 'Graduate Fellow-extrnly funded',
        'empl_status': 'A',
        'deptid': '11093',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2019,5,27,0,0),
        'position_entry_dt': datetime.datetime(2019,5,27,0,0),
    },
    {
        'emplid': '5491169',
        'empl_rcdno': '0',
        'effdt': datetime.datetime(2019,5,27,0,0),
        'effseq': '1',
        'position_nbr': '313497',
        'jobcode': '9566',
        'jobcode_descr': 'Graduate Fellow-extrnly funded',
        'empl_status': 'A',
        'deptid': '11093',
        'um_campus': 'TXXX',
        'status_flg': 'H',
        'job_entry_dt': datetime.datetime(2019,5,27,0,0),
        'position_entry_dt': datetime.datetime(2019,5,27,0,0),
    },
    {
        'emplid': '5491169',
        'empl_rcdno': '0',
        'effdt': datetime.datetime(2019,9,2,0,0),
        'effseq': '0',
        'position_nbr': '313497',
        'jobcode': '9566',
        'jobcode_descr': 'Graduate Fellow-extrnly funded',
        'empl_status': 'A',
        'deptid': '11093',
        'um_campus': 'TXXX',
        'status_flg': 'C',
        'job_entry_dt': datetime.datetime(2019,5,27,0,0),
        'position_entry_dt': datetime.datetime(2019,5,27,0,0),
    },
]

entry_groups = [
    {
        'position_nbr': '274940',
        'job_entry_dt': datetime.datetime(2018,8,27,0,0),
        'jobcode': '9561',
        'deptid': '11093',
        'entries': entries[0:1],
    },
    {
        'position_nbr': '286129',
        'job_entry_dt': datetime.datetime(2019,5,27,0,0),
        'jobcode': '9566',
        'deptid': '11093',
        'entries': entries[1:2],
    },
    {
        'position_nbr': '313497',
        'job_entry_dt': datetime.datetime(2019,5,27,0,0),
        'jobcode': '9566',
        'deptid': '11093',
        'entries': entries[2:],
    },
]

jobs = [
    {
        'affiliation_id': '9561',
        'deptid': '11093',
        'um_campus': 'TXXX',
        'org_id': 'OTQFKMQEJM',
        'empl_rcdno': '0',
        'job_title': 'Graduate School Fellow',
        'job_description': 'Graduate School Fellow',
        'employment_type': 'student',
        'staff_type': 'nonacademic',
        'start_date': datetime.datetime(2018,8,27,0,0),
        'end_date': datetime.datetime(2018,8,27,0,0),
        'visibility': 'Restricted',
        'profiled': False,
    },
    {
        'affiliation_id': '9566',
        'deptid': '11093',
        'um_campus': 'TXXX',
        'org_id': 'OTQFKMQEJM',
        'empl_rcdno': '0',
        'job_title': 'Graduate Fellow-extrnly funded',
        'job_description': 'Graduate Fellow',
        'employment_type': 'student',
        'staff_type': 'nonacademic',
        'start_date': datetime.datetime(2019,5,27,0,0),
        'end_date': datetime.datetime(2019,5,27,0,0),
        'visibility': 'Restricted',
        'profiled': False,
    },
    {
        'affiliation_id': '9566',
        'deptid': '11093',
        'um_campus': 'TXXX',
        'org_id': 'OTQFKMQEJM',
        'empl_rcdno': '0',
        'job_title': 'Graduate Fellow-extrnly funded',
        'job_description': 'Graduate Fellow',
        'employment_type': 'student',
        'staff_type': 'nonacademic',
        'start_date': datetime.datetime(2019,5,27,0,0),
        'end_date': None,
        'visibility': 'Restricted',
        'profiled': False,
    },
]
