import datetime

entries = [
  {
    'emplid': '2898289',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2015,9,7,0,0),
    'effseq': '0',
    'position_nbr': '251716',
    'jobcode': '9560',
    'jobcode_descr': 'Post-Doctoral Fellow',
    'empl_status': 'A',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'status_flg': 'H',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2015,9,7,0,0),
  },
  {
    'emplid': '2898289',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2015,9,7,0,0),
    'effseq': '1',
    'position_nbr': '251716',
    'jobcode': '9560',
    'jobcode_descr': 'Post-Doctoral Fellow',
    'empl_status': 'A',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'status_flg': 'H',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2015,9,7,0,0),
  },
  {
    'emplid': '2898289',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2015,12,14,0,0),
    'effseq': '0',
    'position_nbr': '251716',
    'jobcode': '9560',
    'jobcode_descr': 'Post-Doctoral Fellow',
    'empl_status': 'A',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'status_flg': 'H',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2015,9,7,0,0),
  },
  {
    'emplid': '2898289',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2016,7,1,0,0),
    'effseq': '0',
    'position_nbr': '251716',
    'jobcode': '9560',
    'jobcode_descr': 'Post-Doctoral Fellow',
    'empl_status': 'T',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'status_flg': 'H',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2015,9,7,0,0),
  },
  {
    'emplid': '2898289',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2016,8,22,0,0),
    'effseq': '0',
    'position_nbr': '251716',
    'jobcode': '9560',
    'jobcode_descr': 'Post-Doctoral Fellow',
    'empl_status': 'A',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'status_flg': 'H',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2015,9,7,0,0),
  },
  {
    'emplid': '2898289',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2016,8,28,0,0),
    'effseq': '0',
    'position_nbr': '251716',
    'jobcode': '9560',
    'jobcode_descr': 'Post-Doctoral Fellow',
    'empl_status': 'A',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'status_flg': 'H',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2015,9,7,0,0),
  },
  {
    'emplid': '2898289',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2017,2,20,0,0),
    'effseq': '0',
    'position_nbr': '251716',
    'jobcode': '9560',
    'jobcode_descr': 'Post-Doctoral Fellow',
    'empl_status': 'A',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'status_flg': 'H',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2015,9,7,0,0),
  },
  {
    'emplid': '2898289',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2017,6,16,0,0),
    'effseq': '0',
    'position_nbr': '251716',
    'jobcode': '9560',
    'jobcode_descr': 'Post-Doctoral Fellow',
    'empl_status': 'A',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'status_flg': 'H',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2015,9,7,0,0),
  },
  {
    'emplid': '2898289',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2017,6,30,0,0),
    'effseq': '0',
    'position_nbr': '251716',
    'jobcode': '9560',
    'jobcode_descr': 'Post-Doctoral Fellow',
    'empl_status': 'A',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'status_flg': 'H',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2015,9,7,0,0),
  },
  {
    'emplid': '2898289',
    'empl_rcdno': '1',
    'effdt': datetime.datetime(2017,7,10,0,0),
    'effseq': '0',
    'position_nbr': '251716',
    'jobcode': '9560',
    'jobcode_descr': 'Post-Doctoral Fellow',
    'empl_status': 'T',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'status_flg': 'C',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'position_entry_dt': datetime.datetime(2015,9,7,0,0),
  },
]

entry_groups = [
  {
    'position_nbr': '251716',
    'job_entry_dt': datetime.datetime(2015,9,7,0,0),
    'jobcode': '9560',
    'deptid': '11245',
    'entries': entries,
  },
]

jobs = [
  {
    'affiliation_id': '9560',
    'deptid': '11245',
    'um_campus': 'TXXX',
    'org_id': 'ZWLCEAOWFEA',
    'empl_rcdno': '1',
    'job_title': 'Post-Doctoral Fellow',
    'job_description': 'Post-Doctoral Fellow',
    'employment_type': 'pit',
    'staff_type': 'nonacademic',
    'start_date': datetime.datetime(2015,9,7,0,0),
    'end_date': datetime.datetime(2017,7,10,0,0),
    'visibility': 'Restricted',
    'profiled': False,
  },
]

# TODO: Not sure what to do with primary jobs in this case yet,
# especially because this person also has employee jobs!
#jobs_with_primary = []
#jobs_with_primary.append({**jobs[-1], **{'primary': True}})
#
## Set according to the primary job:
#transformed_profiled = False

#jobs_with_transformed_staff_type = []
#for job in jobs_with_primary:
#  jobs_with_transformed_staff_type.append({**job, **{'staff_type': 'nonacademic'}})
#
#jobs_with_staff_org_assoc_id = [
#  {**jobs_with_primary[3], **{'staff_org_assoc_id': 'autoid:6030-PIXEZPPAPIRGQ-Administrative Manager 2-exec_admin_manage-2017-07-10'}},
#  {**jobs_with_primary[1], **{'staff_org_assoc_id': 'autoid:6030-PIXEZPPAPIRGQ-Senior Research Fellow-researcher-2000-11-22'}},
#  {**jobs_with_primary[2], **{'staff_org_assoc_id': 'autoid:6030-PIXEZPPAPIRGQ-Post-Doctoral Fellow-researcher-2015-09-07',}}
#]
